#!/bin/bash
#
# version-bump.sh - Unified version management for MinnowVPN
#
# Usage:
#   ./scripts/version-bump.sh patch              # 1.0.0 -> 1.0.1
#   ./scripts/version-bump.sh minor              # 1.0.0 -> 1.1.0
#   ./scripts/version-bump.sh major              # 1.0.0 -> 2.0.0
#   ./scripts/version-bump.sh 2.0.0-beta.1       # Explicit version
#   ./scripts/version-bump.sh --dry-run patch    # Preview changes
#   ./scripts/version-bump.sh --current          # Show current version
#

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="$PROJECT_ROOT/VERSION"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] <bump-type|version>

Arguments:
  bump-type    One of: major, minor, patch
  version      Explicit semver (e.g., 1.2.3 or 1.2.3-beta.1)

Options:
  --dry-run    Show what would change without modifying files
  --current    Show current version and exit
  --help       Show this help message

Examples:
  $(basename "$0") patch                    # 1.0.0 -> 1.0.1
  $(basename "$0") minor                    # 1.0.0 -> 1.1.0
  $(basename "$0") major                    # 1.0.0 -> 2.0.0
  $(basename "$0") 2.0.0-beta.1             # Explicit version
  $(basename "$0") --dry-run patch          # Preview changes
EOF
    exit 0
}

# Parse semver into components
parse_semver() {
    local version="$1"
    # Extract base version (before any pre-release tag)
    local base_version="${version%%-*}"

    # Split into major.minor.patch
    IFS='.' read -r MAJOR MINOR PATCH <<< "$base_version"

    # Extract pre-release if present
    if [[ "$version" == *"-"* ]]; then
        PRERELEASE="${version#*-}"
    else
        PRERELEASE=""
    fi
}

# Validate semver format
validate_semver() {
    local version="$1"
    if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
        log_error "Invalid semver format: $version"
        log_error "Expected format: X.Y.Z or X.Y.Z-prerelease"
        exit 1
    fi
}

# Calculate Flutter build number: major*10000 + minor*100 + patch
calc_build_number() {
    local version="$1"
    parse_semver "$version"
    echo $((MAJOR * 10000 + MINOR * 100 + PATCH))
}

# Get current version from VERSION file
get_current_version() {
    if [[ ! -f "$VERSION_FILE" ]]; then
        log_error "VERSION file not found at $VERSION_FILE"
        exit 1
    fi
    cat "$VERSION_FILE" | tr -d '\n'
}

# Calculate new version based on bump type
bump_version() {
    local current="$1"
    local bump_type="$2"

    parse_semver "$current"

    case "$bump_type" in
        major)
            echo "$((MAJOR + 1)).0.0"
            ;;
        minor)
            echo "${MAJOR}.$((MINOR + 1)).0"
            ;;
        patch)
            echo "${MAJOR}.${MINOR}.$((PATCH + 1))"
            ;;
        *)
            # Assume explicit version
            echo "$bump_type"
            ;;
    esac
}

# Generate version.dart file content
generate_version_dart() {
    local version="$1"
    local build_number="$2"
    local git_commit="$3"
    local build_date="$4"

    cat << EOF
// GENERATED FILE - DO NOT EDIT
// Generated by scripts/version-bump.sh

/// Application version information
class AppVersion {
  /// Semantic version string (e.g., "1.0.0" or "1.0.0-beta.1")
  static const String version = '$version';

  /// Build number for app stores (derived from version: major*10000 + minor*100 + patch)
  static const int buildNumber = $build_number;

  /// Git commit hash (short form)
  static const String gitCommit = '$git_commit';

  /// Build timestamp (ISO 8601)
  static const String buildDate = '$build_date';

  /// Full version string for display
  static const String fullVersion = '$version ($git_commit)';
}
EOF
}

# Update a file with sed (macOS compatible)
update_file() {
    local file="$1"
    local pattern="$2"
    local replacement="$3"
    local dry_run="$4"

    if [[ "$dry_run" == "true" ]]; then
        echo "  Would update: $file"
        echo "    Pattern: $pattern"
        echo "    Replace: $replacement"
    else
        # Use different sed syntax for macOS vs Linux
        if [[ "$(uname)" == "Darwin" ]]; then
            sed -i '' "$pattern" "$file"
        else
            sed -i "$pattern" "$file"
        fi
        log_success "Updated $file"
    fi
}

# Main function
main() {
    local dry_run="false"
    local bump_type=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                dry_run="true"
                shift
                ;;
            --current)
                echo "$(get_current_version)"
                exit 0
                ;;
            --help|-h)
                usage
                ;;
            *)
                bump_type="$1"
                shift
                ;;
        esac
    done

    if [[ -z "$bump_type" ]]; then
        log_error "Missing bump type or version"
        usage
    fi

    # Get current version
    local current_version
    current_version=$(get_current_version)
    log_info "Current version: $current_version"

    # Calculate new version
    local new_version
    if [[ "$bump_type" =~ ^(major|minor|patch)$ ]]; then
        new_version=$(bump_version "$current_version" "$bump_type")
    else
        new_version="$bump_type"
    fi

    # Validate new version
    validate_semver "$new_version"

    log_info "New version: $new_version"

    # Calculate build number and get metadata
    local build_number
    build_number=$(calc_build_number "$new_version")
    log_info "Build number: $build_number"

    local git_commit
    git_commit=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    log_info "Git commit: $git_commit"

    local build_date
    build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    log_info "Build date: $build_date"

    # Strip pre-release for files that don't support it
    local base_version="${new_version%%-*}"

    echo ""
    if [[ "$dry_run" == "true" ]]; then
        log_warn "DRY RUN - No files will be modified"
        echo ""
    fi

    # Update VERSION file
    if [[ "$dry_run" == "true" ]]; then
        echo "  Would update: VERSION"
        echo "    Content: $new_version"
    else
        echo "$new_version" > "$VERSION_FILE"
        log_success "Updated VERSION"
    fi

    # Update Cargo.toml (uses base version without pre-release)
    update_file "$PROJECT_ROOT/Cargo.toml" \
        "s/^version = \".*\"/version = \"$base_version\"/" \
        "version = \"$base_version\"" \
        "$dry_run"

    # Update minnowvpn-server/pubspec.yaml
    update_file "$PROJECT_ROOT/minnowvpn-server/pubspec.yaml" \
        "s/^version: .*/version: $new_version/" \
        "version: $new_version" \
        "$dry_run"

    # Update minnowvpn_client/pubspec.yaml (with build number)
    update_file "$PROJECT_ROOT/minnowvpn_client/pubspec.yaml" \
        "s/^version: .*/version: $base_version+$build_number/" \
        "version: $base_version+$build_number" \
        "$dry_run"

    # Update minnowvpn_console/pubspec.yaml (with build number)
    update_file "$PROJECT_ROOT/minnowvpn_console/pubspec.yaml" \
        "s/^version: .*/version: $base_version+$build_number/" \
        "version: $base_version+$build_number" \
        "$dry_run"

    # Update Windows NSIS installer
    update_file "$PROJECT_ROOT/installer/windows/minnowvpn.nsi" \
        "s/^!define PRODUCT_VERSION \".*\"/!define PRODUCT_VERSION \"$new_version\"/" \
        "!define PRODUCT_VERSION \"$new_version\"" \
        "$dry_run"

    # Generate version.dart files
    local version_dart_content
    version_dart_content=$(generate_version_dart "$new_version" "$build_number" "$git_commit" "$build_date")

    if [[ "$dry_run" == "true" ]]; then
        echo "  Would generate: minnowvpn_client/lib/version.dart"
        echo "  Would generate: minnowvpn_console/lib/version.dart"
    else
        echo "$version_dart_content" > "$PROJECT_ROOT/minnowvpn_client/lib/version.dart"
        log_success "Generated minnowvpn_client/lib/version.dart"

        echo "$version_dart_content" > "$PROJECT_ROOT/minnowvpn_console/lib/version.dart"
        log_success "Generated minnowvpn_console/lib/version.dart"
    fi

    echo ""
    if [[ "$dry_run" == "true" ]]; then
        log_warn "DRY RUN complete - no files were modified"
    else
        log_success "Version bumped from $current_version to $new_version"
        echo ""
        echo "Files updated:"
        echo "  - VERSION"
        echo "  - Cargo.toml"
        echo "  - minnowvpn-server/pubspec.yaml"
        echo "  - minnowvpn_client/pubspec.yaml"
        echo "  - minnowvpn_console/pubspec.yaml"
        echo "  - installer/windows/minnowvpn.nsi"
        echo "  - minnowvpn_client/lib/version.dart"
        echo "  - minnowvpn_console/lib/version.dart"
    fi
}

main "$@"
