// GENERATED FILE - DO NOT EDIT
// Generated by scripts/version-bump.sh

/// Application version information
class AppVersion {
  /// Semantic version string (e.g., "1.0.0" or "1.0.0-beta.1")
  static const String version = '1.0.0';

  /// Build number for app stores (derived from version: major*10000 + minor*100 + patch)
  static const int buildNumber = 10000;

  /// Git commit hash (short form)
  static const String gitCommit = 'f7b182a';

  /// Build timestamp (ISO 8601)
  static const String buildDate = '2026-02-02T00:38:23Z';

  /// Full version string for display
  static const String fullVersion = '1.0.0 (f7b182a)';
}
